# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Christopher Silva
subtitle: Software Enginner

authors:
  name: "Christopher Silva"
  avatar: "/images/avatar_200.jpg"
  description: "Software Engineer {Who am I?} #dad #footballlover #beerlover"

socialsmedia:
  0:
    label: "Twitter"
    link: "http://twitter.com/xiris_"
    icon: fa-twitter
  1:
    label: "Github"
    link: "http://github.com/xiris"
    icon: fa-github
  2:
    label: "Linkedin"
    link: "http://de.linkedin.com/in/xiris"
    icon: fa-linkedin
  3:
    label: "Email"
    link: "mailto: xiris@xiris.com.br"
    icon: fa-envelope-o

disqus:
  shortname: xiris
